---
title: "corHMM Model Statistics"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
knitr::opts_knit$set(echo = TRUE,warning = FALSE, message = FALSE)  
knitr::opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/') 
```

# Environment
```{r}
packages <- c("tidyverse","kableExtra","tableone") 
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T)) 
# Load function
source('./lib/consistent_themes.R')
# Print
Sys.info()
sessionInfo() 
``` 

# Load corHMM output
```{r}
corHMM_one_rate_ER <- readRDS("./data/corHMM_rate_differences/corHMM_single_ER.RDS")
corHMM_one_rate_ARD <-  readRDS("./data/corHMM_rate_differences/corHMM_single_ARD.RDS")
corHMM_two_rates_ER <-  readRDS("./data/corHMM_rate_differences/corHMM_two_ER.RDS")
corHMM_two_rates_ARD <-  readRDS("./data/corHMM_rate_differences/corHMM_two_ARD.RDS")
```

# Get model statistics 
```{r}
pheno = names(corHMM_one_rate_ER)
# One rates
corHMM_one_rate_ER_stats <- lapply(corHMM_one_rate_ER,phyloAMR::characterize_asr_model) %>% do.call(rbind,.) %>% mutate(phenotype = pheno)
corHMM_one_rate_ARD_stats <- lapply(corHMM_one_rate_ARD,phyloAMR::characterize_asr_model) %>% do.call(rbind,.) %>% mutate(phenotype = pheno)

# Two rates
characterize_two_cat_corHMM_model <- function(corHMM_obj){
  model <- ifelse(c(corHMM_obj[["index.mat"]] %>% as.vector() %>% subset(is.na(.)==F) %>% unique %>% length)==4,"ER","ARD")
  category1_rate1 <- corHMM_obj$solution[2,1]
  category2_rate1 <- corHMM_obj$solution[3,4]
  if(model=="ER"){
    category1_rate2 <- NA
    category2_rate2 <- NA
  } else {
    category1_rate2 <- corHMM_obj$solution[1,2]
    category2_rate2 <-   corHMM_obj$solution[4,3]
  }  
  multi_np = max(unlist(corHMM_obj$index.mat),na.rm=T)
  multi_nRateCat = corHMM_obj$rate.cat
  multi_loglik = corHMM_obj$loglik
  multi_AIC = corHMM_obj$AIC
  multi_AICc = corHMM_obj$AICc
  data <- data.frame(model,multi_np,multi_nRateCat,category1_rate1,category1_rate2,category2_rate1,category2_rate2,multi_loglik,multi_AIC,multi_AICc)
  return(data)
}

corHMM_two_rates_ER_stats <- lapply(corHMM_two_rates_ER,characterize_two_cat_corHMM_model) %>% do.call(rbind,.) %>% mutate(phenotype = pheno)

corHMM_two_rates_ARD_stats <- lapply(corHMM_two_rates_ARD,characterize_two_cat_corHMM_model) %>% do.call(rbind,.) %>% mutate(phenotype = pheno)
```

# Curate table
```{r}
joint_ER_df <- left_join(corHMM_one_rate_ER_stats,corHMM_two_rates_ER_stats) 
joint_ARD_df <-  left_join(corHMM_one_rate_ARD_stats,corHMM_two_rates_ARD_stats) 

total_df <- rbind(joint_ER_df,joint_ARD_df)
total_df$best_model <- ifelse(total_df$AIC < total_df$multi_AIC,"One rate category","Two rate categories")
favorite_kable(total_df)
```

# Save
```{r}
saveRDS(total_df,'./data/corHMM_rate_differences/corHMM_model_stats.RDS')
```
