---
title: "Adjusted regression for resistance outcomes and ST258 clade"
output: html_document
date: "`r Sys.Date()`"
--- 

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/')
```

# Environment
```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse","devtools","kableExtra","cowplot","gridExtra",'forestplot','tableone','phyloAMR','ape')   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

#Themes
source("./lib/consistent_themes.R")

# Scripts
source("./lib/common_functions.R")
source("./scripts/figures/figure3.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data
```{r load data,include=T,echo=T,results=F,message=F} 
tr <- read.tree("./data/tree/tree.treefile")      
df <- readRDS("./data/dataset/df.RDS")
```

# Curate exposures 
```{r}
rownames(df) <- df$isolate_no    
df$clade_I <- factor(df$clade_I,levels = c("Clade II","Clade I"))

# Create factor variables to help regression 
factor_vars_df <- df %>% select(clade_I,sex) %>% as.data.frame()

# List of resistance columns to convert to factor
drugs <- c("TMP_SMX","gentamicin","AMK","CST","blbli")
phenotypes <- c(paste0(drugs,"_dich_num"))

# Convert specified columns to factor
resistance <- df %>% select(phenotypes) %>% mutate_all(as.factor) 

df_fin <- cbind.data.frame(resistance,factor_vars_df,df %>% select(isolate_no,Patient_ID,Cx_date,age))
```

# Load asr data and generate a drug's dataset
```{r}
# Load asr
pheno <- c("TMP_SMX","gentamicin","AMK","CST","blbli")
for(i in pheno){
  assign(paste0(i,"_asr_clustering"),readRDS(paste0("./data/asr_clustering/",i,"_asr_clustering.RDS")))
}

# Create dataset
for(i in pheno){
  asr_df <- get(paste0(i,"_asr_clustering"))
  df_w_asr <- df_fin %>% left_join(asr_df %>% mutate(isolate_no = child_name))
  assign(paste0(i,"_regression_df"),df_w_asr)
}
```

# LR analyses 
# Modeling 
```{r,warning=F,message=F}
variables_of_interest <- c("age",'sex',"clade_I")
TMP_SMX_lr <- phyloaware_regression("TMP_SMX_dich_num",df = TMP_SMX_regression_df, variables = variables_of_interest ,first_present = T,patient_id = 'Patient_ID',culture_date = "Cx_date",multivariable = 'multivariable')

gentamicin_lr <- phyloaware_regression("gentamicin_dich_num",gentamicin_regression_df,variables = variables_of_interest,first_present = T,patient_id = 'Patient_ID',culture_date = "Cx_date",multivariable = 'multivariable') 

AMK_lr <- phyloaware_regression("AMK_dich_num",AMK_regression_df,variables = variables_of_interest ,first_present = T,patient_id = 'Patient_ID',culture_date = "Cx_date",multivariable = 'multivariable')
CST_lr <- phyloaware_regression("CST_dich_num",CST_regression_df,variables = variables_of_interest, first_present = T,patient_id = 'Patient_ID',culture_date = "Cx_date",multivariable = 'multivariable')
blbli_lr <- phyloaware_regression("blbli_dich_num",blbli_regression_df,variables =variables_of_interest, first_present = T,patient_id = 'Patient_ID',culture_date = "Cx_date",multivariable = 'multivariable')
```

# Generate descriptive stats
```{r}
get_mv_table_adjusted <- function(datasets,lr_results){
  # Nons
  nons_modeling <- cbind.data.frame(datasets[[1]] ,lr_results[[1]]) %>%  as.data.frame %>% mutate(outcome = "present") %>% subset(!rownames(.) %in% c("age","sexmale")) %>% `rownames<-`(NULL)
  # Emergence
  emergence_modeling <- cbind.data.frame(datasets[[2]] ,lr_results[[2]])%>%  as.data.frame %>% mutate(outcome = "singleton")  %>% subset(!rownames(.) %in% c("age","sexmale"))   %>% `rownames<-`(NULL)
  # Spread
  spread_modeling <- cbind.data.frame(datasets[[3]] ,lr_results[[3]]) %>%  as.data.frame %>% mutate(outcome = "cluster") %>% subset(!rownames(.) %in% c("age","sexmale"))  %>% `rownames<-`(NULL)
  final_list <- rbind(nons_modeling,emergence_modeling,spread_modeling)
  return(final_list)
}
```

```{r} 
TMP_SMX_descriptive <- generate_descriptive_stats("TMP_SMX",TMP_SMX_lr$datasets,variables = "clade_I",factorVars = "clade_I")
TMP_SMX_results <- get_mv_table_adjusted(datasets = TMP_SMX_descriptive,lr_results=TMP_SMX_lr$multivariable)

gentamicin_descriptive <- generate_descriptive_stats("gentamicin",gentamicin_lr$datasets,"clade_I",factorVars = "clade_I")
gentamicin_results <- get_mv_table_adjusted(datasets = gentamicin_descriptive,lr_results=gentamicin_lr$multivariable)

AMK_descriptive <- generate_descriptive_stats("AMK",AMK_lr$datasets,"clade_I",factorVars = "clade_I")
AMK_results <- get_mv_table_adjusted(datasets = AMK_descriptive,lr_results=AMK_lr$multivariable)

CST_descriptive <- generate_descriptive_stats("CST",CST_lr$datasets,"clade_I",factorVars = "clade_I")
CST_results <- get_mv_table_adjusted(datasets = CST_descriptive,lr_results=CST_lr$multivariable)

blbli_descriptive <- generate_descriptive_stats("blbli",blbli_lr$datasets,"clade_I",factorVars = "clade_I")
blbli_results <- get_mv_table_adjusted(datasets = blbli_descriptive,lr_results=blbli_lr$multivariable)
```

```{r}  
combined_dataset <- rbind(TMP_SMX_results,gentamicin_results,AMK_results,CST_results,blbli_results)
```

# Forest plot
```{r,fig.height=8.4,fig.width=14}
agent_string <- c("TMP-SMX","","","","Gentamicin","","","","Amikacin","","","","Colistin","","","","BL/BLI","","","")
susceptible_string <- c("",subset(TMP_SMX_results,outcome=="present") %>% .$susceptible,"","","",subset(gentamicin_results,outcome=="present") %>% .$susceptible,"","","",subset(AMK_results,outcome=="present") %>% .$susceptible,"","","",subset(CST_results,outcome=="present") %>% .$susceptible,"","","",subset(blbli_results,outcome=="present") %>% .$susceptible,"","")
feature_string <- c("","Presence","Emergence","Spread","","Presence","Emergence","Spread","","Presence","Emergence","Spread","","Presence","Emergence","Spread","","Presence","Emergence","Spread")
resistance_string <- c("",TMP_SMX_results$non_susceptible,"",gentamicin_results$non_susceptible,"",AMK_results$non_susceptible,"",CST_results$non_susceptible,"",blbli_results$non_susceptible)
OR_string <- c("",TMP_SMX_results$`OR (95% CI)`,"",gentamicin_results$`OR (95% CI)`,"",AMK_results$`OR (95% CI)`,"",CST_results$`OR (95% CI)`,"",blbli_results$`OR (95% CI)`)%>% str_pad(.,width=19,side='right', pad = "\u00A0")
 
tabletext <- cbind.data.frame(agent_string,susceptible_string,feature_string,resistance_string,OR_string) %>% `colnames<-`(c("agent","susceptible","feature","resistance","OR"))

# Metadata
OR_stat <- c("",TMP_SMX_results$`OR (95% CI)`,"",gentamicin_results$`OR (95% CI)`,"",AMK_results$`OR (95% CI)`,"",CST_results$`OR (95% CI)`,"",blbli_results$`OR (95% CI)`)
OR <- sapply(OR_stat,FUN=function(x){str_split(x," ",simplify=T) %>% .[,1] %>% as.numeric})
lower <- sapply(OR_stat,FUN=function(x){
    initial_split <- str_split(x," ",simplify=T)
    if(ncol(initial_split)==1){
        ""
    } else {
        initial_split[,2] %>% str_split(.,"\\-",simplify=T) %>% .[,1] %>% gsub("\\(","",.) %>% as.numeric
    }})
upper <- sapply(OR_stat,FUN=function(x){
    initial_split <- str_split(x," ",simplify=T)
    if(ncol(initial_split)==1){
        ""
    } else {
        initial_split[,2] %>% str_split(.,"\\-",simplify=T) %>% .[,2] %>% gsub("\\)","",.) %>% as.numeric
}})    
    
fp_rmetadata <- cbind.data.frame(OR,lower,upper)  %>% mutate_all(as.numeric)
  
forest_plot <- res_forest_plot(tabletext = tabletext,fp_rmetadata = fp_rmetadata,outcome_name="ST258 Clade I",type_of_regression="Adjusted") 

forest_plot
```

# Save in regression data folder
```{r}
saveRDS(forest_plot,"./data/regression/adjusted_regression_clade_figure.RDS")
```
