---
title: "Adjusted regression for resistance outcomes and dysbiotic agents"
output: html_document
date: "`r Sys.Date()`"
--- 

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/')
```

# Environment
```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse","devtools","kableExtra","cowplot","gridExtra",'forestplot','tableone','phyloAMR','ape')   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

#Themes
source("./lib/consistent_themes.R")

# Scripts
source("./lib/common_functions.R")
source("./scripts/figures/figure3.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data
```{r load data,include=T,echo=T,results=F,message=F} 
tr <- read.tree("./data/tree/tree.treefile")      
df <- readRDS("./data/dataset/df.RDS")
``` 

# Curate exposures 
```{r}
rownames(df) <- df$isolate_no   

# Dysbiosis Metric
dysbiosis <- c("cefepime_1d" , "ceftaroline_1d" , "ceftazidime_1d"  , "ctx_1d" , "cipro_1d", "erta_1d" , "flagyl_1d" , "imipenem_1d" , "levo_1d" , "meropenem_1d", "zosyn_1d") 
df$dysbiosis_abx <- df %>% select(dysbiosis) %>% {ifelse(rowSums(.)>1,1,0)}

# Create factor variables to help regression 
factor_vars_df <- df %>% select(dysbiosis_abx) %>% as.data.frame()

# convert "yes"  "no" and 10
factor_vars_df <- apply(factor_vars_df,2,FUN=function(x){
  ifelse(x=="yes",1,ifelse(x=="no",0,x)) %>% as.numeric
}) %>% as.data.frame %>% `rownames<-`(df$isolate_no)

# List of resistance columns to convert to factor
drugs <- c("TMP_SMX","gentamicin","AMK","CST","blbli")
phenotypes <- c(paste0(drugs,"_dich_num"))

# Convert specified columns to factor
resistance <- df %>% select(phenotypes) %>% mutate_all(as.factor) 

df_fin <- cbind.data.frame(resistance,factor_vars_df,df %>% select(isolate_no,Patient_ID,Cx_date,age,sex))
```

```{r}
# Load asr
pheno <- c("TMP_SMX","gentamicin","AMK","CST","blbli")
for(i in pheno){
  assign(paste0(i,"_asr_clustering"),readRDS(paste0("./data/asr_clustering/",i,"_asr_clustering.RDS")))
}

# Create dataset
for(i in pheno){
  asr_df <- get(paste0(i,"_asr_clustering"))
  df_w_asr <- df_fin %>% left_join(asr_df %>% mutate(isolate_no = child_name))
  assign(paste0(i,"_regression_df"),df_w_asr)
}
```

# LR analyses 
# Modeling 
```{r,warning=F,message=F}
variables_of_interest <- c("age",'sex',"dysbiosis_abx")
TMP_SMX_lr <- phyloaware_regression(trait = "TMP_SMX_dich_num", df = TMP_SMX_regression_df,variables = variables_of_interest, first_present = T, patient_id = 'Patient_ID',culture_date = "Cx_date",multivariable = 'multivariable', stepwise_direction = NULL, entry_criteria = NULL, retention_criteria = NULL, confounding_criteria = NULL)
gentamicin_lr <- phyloaware_regression(trait = "gentamicin_dich_num",df=gentamicin_regression_df,variables = variables_of_interest,first_present = T,patient_id = 'Patient_ID',culture_date = "Cx_date",multivariable = 'multivariable')   
AMK_lr <- phyloaware_regression(trait = "AMK_dich_num",df=AMK_regression_df,variables = variables_of_interest,first_present = T,patient_id = 'Patient_ID',culture_date = "Cx_date",multivariable = 'multivariable')
CST_lr <- phyloaware_regression(trait="CST_dich_num",df=CST_regression_df,variables = variables_of_interest,first_present = T,patient_id = 'Patient_ID',culture_date = "Cx_date",multivariable = 'multivariable')
blbli_lr <- phyloaware_regression(trait = "blbli_dich_num",df=blbli_regression_df,variables =variables_of_interest,first_present = T,patient_id = 'Patient_ID',culture_date = "Cx_date",multivariable = 'multivariable')  
```

# Generate descriptive stats 
```{r} 
TMP_SMX_descriptive <- generate_descriptive_stats("TMP_SMX",TMP_SMX_lr$datasets,variables = "dysbiosis_abx",factorVars = "dysbiosis_abx")
TMP_SMX_results <- get_mv_table_adjusted(descriptives = TMP_SMX_descriptive,lr_results=TMP_SMX_lr$multivariable)  

gentamicin_descriptive <- generate_descriptive_stats("gentamicin",gentamicin_lr$datasets,"dysbiosis_abx",factorVars = "dysbiosis_abx")
gentamicin_results <- get_mv_table_adjusted(descriptives = gentamicin_descriptive,lr_results=gentamicin_lr$multivariable)

AMK_descriptive <- generate_descriptive_stats("AMK",AMK_lr$datasets,"dysbiosis_abx",factorVars = "dysbiosis_abx")
AMK_results <- get_mv_table_adjusted(descriptives = AMK_descriptive,lr_results=AMK_lr$multivariable)

CST_descriptive <- generate_descriptive_stats("CST",CST_lr$datasets,"dysbiosis_abx",factorVars = "dysbiosis_abx")
CST_results <- get_mv_table_adjusted(descriptives = CST_descriptive,lr_results=CST_lr$multivariable)

blbli_descriptive <- generate_descriptive_stats("blbli",blbli_lr$datasets,"dysbiosis_abx",factorVars = "dysbiosis_abx")
blbli_results <- get_mv_table_adjusted(descriptives = blbli_descriptive,lr_results=blbli_lr$multivariable)
```

# Forest plot
```{r,fig.height=8.4,fig.width=14}
tabletext <- get_table_text(TMP_SMX_results,gentamicin_results,AMK_results,CST_results,blbli_results)
fp_rmetadata <- get_fp_rmetadata(TMP_SMX_results,gentamicin_results,AMK_results,CST_results,blbli_results)

forest_plot <- res_forest_plot(tabletext = tabletext,fp_rmetadata = fp_rmetadata,outcome_name="Dybsiotic antibiotic",type_of_regression="Adjusted") 
forest_plot
```

# Save in regression data folder
```{r}
saveRDS(forest_plot,"./data/regression/adjusted_regression_dysbiotic_figure.RDS")
```
