---
title: "purposeful_selection"
author: "Kyle Gontjes"
date: '`r Sys.Date()`'
output: html_document
---


```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/')
```

```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse",'phylosuite')   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))  
# Print
Sys.info()
sessionInfo() 
``` 

```{r}
df <- readRDS("./data/regression/regression_df.RDS")
eligible_variables <- readLines("./data/regression/eligible_variables.txt")

# Load asr
pheno <- c("TMP_SMX","gentamicin","AMK","CST","blbli")
for(i in pheno){
  assign(paste0(i,"_asr_clustering"),readRDS(paste0("./data/asr_clustering/",i,"_asr_clustering.RDS")))
}

# Create dataset
for(i in pheno){
  asr_df <- get(paste0(i,"_asr_clustering"))
  df_w_asr <- df %>% left_join(asr_df %>% mutate(isolate_no = child_name))
  assign(paste0(i,"_regression_df"),df_w_asr)
}
```

```{r} 
purposeful_output <- lapply(pheno,FUN=function(x){
  phenotype = paste0(x,"_dich_num")
  phenotype_df = get(paste0(x,"_regression_df"))
  phylosuite::phyloaware_regression(phenotype,variables =eligible_variables,df=phenotype_df,first_present=T,patient_id="Patient_ID",culture_date="Cx_date",multivariable='purposeful',stepwise_direction = NULL,entry_criteria = 0.25,retention_criteria = 0.1,confounding_criteria = 0.2)
}) %>% `names<-`(pheno)

saveRDS(purposeful_output,"./data/regression/purposeful_regression_results.RDS")
```
