---
title: "results_section_4"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/')
```
# Environment
```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse","cowplot",'ComplexHeatmap','ggVennDiagram')   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Functions
source("./lib/common_functions.R")
source('./lib/consistent_themes.R')

# Print environment
Sys.info()
sessionInfo()
```

# Load data
```{r}
phyloaware_regression_obj <- readRDS("./data/regression/purposeful_regression_results.RDS")
```

# Get model components
```{r}
print_final_model <- function(x){
  tables <- lapply(x,FUN=function(list){
    list[['final_model_table']] %>% arrange(p_value)
  })  %>% `names<-`(c("present","singleton","spread")) 
  
  lapply(tables,function(y){
   if(y %>% as.data.frame %>% nrow()==0){
      paste0(names(y))
      cbind.data.frame(Variable ='No model',`OR (95% CI)` = 'NA',p_value ='NA')
    } 
    if(y %>% as.data.frame %>% nrow()>0){
      paste0(names(y))
      y %>% arrange(p_value) %>% rownames_to_column(.,'Variable') %>% select("Variable","OR (95% CI)","p_value")
    } 
  })
}

cbind_na <- function(df_list) { 
  max_rows <- max(lapply(df_list, nrow) %>% unlist) 
  lapply(df_list,function(x){
    rbind(x,as.data.frame(matrix(NA,nrow = (max_rows - nrow(x)),ncol=ncol(x))) %>% mutate_all(as.character) %>% `colnames<-`(c("Variable","OR (95% CI)","p_value")))
  }) %>% do.call(cbind,.)
}
```

```{r}
drugs <- c("TMP_SMX",'gentamicin','AMK','CST','blbli')
mv_tables <- lapply(drugs,FUN=function(x){
  print_final_model(phyloaware_regression_obj[[x]]$multivariable)  %>% cbind_na
}) %>% `names<-`(drugs)
```

# List model components
```{r}
get_list_of_components <- function(tbl){
  Present =  tbl$present.Variable  %>% subset(.!='NA')
  Emergence = tbl$singleton.Variable   %>% subset(.!='NA')
  Spread = tbl$spread.Variable  %>% subset(.!='NA')
  results <- list(A_Present=Present,B_Emergence=Emergence,C_Spread=Spread)
  return(results)
}

model_lists <- lapply(mv_tables,get_list_of_components) %>% `names<-`(drugs)
```

# Get matrix of demographics, antibiotics, comorbidities
# Uniquity
```{r}
create_venn_diagram_df <- function(variable_list){
overview <- process_region_data(Venn(variable_list))
overview$item <- sapply(overview$item,FUN=function(x){
  if(length(x)==0){
    0
  }else {
    paste0(x,collapse=';')
  }
  
})
as.data.frame(overview)
}

get_shared <- function(variable_list,phyloaware_regression_obj,drug){
  shared <- subset(variable_list,name %in% c("B_Emergence/C_Spread",'A_Present/B_Emergence/C_Spread')) %>% .$item %>% subset(.!='0')  %>% str_split(.,";") %>% unlist
  emergence_model <- phyloaware_regression_obj[[drug]]$multivariable[['singleton']][['final_model_table']] %>% subset(rownames(.) %in% shared) 
  cluster_model <- phyloaware_regression_obj[[drug]]$multivariable[['cluster']][['final_model_table']] %>% subset(rownames(.) %in% shared) 
  results <- list(shared=shared,emergence_model=emergence_model,cluster_model=cluster_model)
  return(results)
}

get_unique <-  function(variable_list,phyloaware_regression_obj,drug){
  emergence <- subset(variable_list,name %in% c("B_Emergence",'A_Present/B_Emergence')) %>% .$item %>% subset(.!='0') %>% str_split(.,";") %>% unlist
  emergence_model <- phyloaware_regression_obj[[drug]]$multivariable[['singleton']][['final_model_table']] %>% subset(rownames(.) %in% emergence) 
  spread <-  subset(variable_list,name %in% c("C_Spread",'A_Present/C_Spread')) %>% .$item %>% subset(.!='0') %>% str_split(.,";") %>% unlist
  cluster_model <- phyloaware_regression_obj[[drug]]$multivariable[['cluster']][['final_model_table']] %>% subset(rownames(.) %in% spread) 
  results <- list(emergence=emergence,emergence_model=emergence_model,spread=spread,cluster_model=cluster_model)
  return(results)
}
 

gent_shared_unique <- create_venn_diagram_df(model_lists$gentamicin)
AMK_shared_unique <- create_venn_diagram_df(model_lists$AMK)
CST_shared_unique <- create_venn_diagram_df(model_lists$CST)
blbli_shared_unique <- create_venn_diagram_df(model_lists$blbli)
```

```{r}
get_overall <- function(drug,model_lists,phyloaware_regression_obj){
  model_shared_unique <- create_venn_diagram_df(model_lists[[drug]])
  model_shared <- get_shared(model_shared_unique,phyloaware_regression_obj,drug) 
  model_unique <- get_unique(model_shared_unique,phyloaware_regression_obj,drug) 
  results <- list(model_shared_unique=model_shared_unique,model_shared=model_shared,model_unique=model_unique)
  return(results)
}
```

```{r}
sharing <- lapply(drugs,get_overall,model_lists = model_lists,phyloaware_regression_obj=phyloaware_regression_obj) %>% `names<-`(drugs)
```

# TMP_smx
```{r}
sharing$TMP_SMX
```

# Gentamicin
```{r}
sharing$gentamicin
```

# Amikacin
```{r}
sharing$AMK
```

# Colistin
```{r}
sharing$CST
```

# BL/BLI
```{r}
sharing$blbli
```
