---
title: 'Results Section 2: Antibiotic susceptibility profiles of clinical carbapenem-resistant Klebsiella pneumoniae isolates'
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/')
```

# Environment

```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse","kableExtra","gontjesr","tableone")   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Scripts
source("./lib/common_functions.R")

#Themes
source("./lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data

```{r load data,include=T,echo=T,results=F,message=F}
# Patient Metadata
df <- readRDS("./data/dataset/df.RDS")
```

# Describe resistance frequency

Note: 1 indicates resistance 

```{r}
pheno_vars <- c("TMP_SMX_dich_num","gentamicin_dich_num","AMK_dich_num","CST_dich_num","blbli_dich_num","MVB_dich_num","IR_dich_num")
convert_tableone_into_df(df,vars=pheno_vars,factorVars = pheno_vars) %>% favorite_kable
```
