---
title: "Results Section 1: Study population"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/')
```

# Environment

```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse")   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
Sys.info()
sessionInfo()
```

# Load data

```{r}
df <- readRDS("./data/dataset/df.RDS")
```

# Overall statistics on cohort

```{r}
paste0("Number of isolates: ",nrow(df))
paste0("Number of unique patients: ",df$Patient_ID %>% unique %>% length)
paste0("Number of LTACHs: ",df$LTACH %>% unique %>% length)
```

# Patient summary highlights dense sampling
```{r}
patient_summaries <- df %>% group_by(Patient_ID) %>% summarise(n=n())
patient_summaries$more_than_one <- ifelse(patient_summaries$n >1,1,0)
table(patient_summaries$n,dnn = "Number of contributed isolates")
paste0("Number of patients contributing more than one isolate: ",sum(patient_summaries$more_than_one))
paste0("Proportion of patients contributing more than one isolate: ",round(sum(patient_summaries$more_than_one) / nrow(patient_summaries) *100,2))
```

# For cohort statistics mentioned in this section, please see supplemental table 4 
