---
title: "Figure 1: Comprehensive sampling of carbapenem-resistant Klebsiella pneumoniae that are resistant to last-resort or recently-introduced antibiotics"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/')
```

# Environment

```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse")   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T)) 
# Functions
source("./lib/common_functions.R")
source('./lib/consistent_themes.R')
# Print
Sys.info()
sessionInfo() 
```

# Load data

```{r}
df <- readRDS("./data/dataset/df.RDS")

get_legend <- function(plot){
  cowplot::get_plot_component(plot,"guide-box",return_all=T) %>% .[[3]]
}
```

# Figure 1: Sampling density
```{r}
phenos <- c("TMP_SMX_dich","gentamicin_dich","AMK_dich",'CST_dich','blbli_dich')
# Study histogram
A <- ggplot(data=df,aes(x=Cx_date)) + geom_histogram(fill='black', bins = 65) + theme_bw_me + xlab("Date of culture collection") + ylab ("No. specimens") + scale_y_continuous(limits = c(0, 20)) + theme(axis.ticks = element_line(color = "black"), axis.text = element_text(color = "black", size = 12), axis.title = element_text(size = 15))
 
# Histogram by facility 
B <- ggplot(data=df,aes(x=LTACH_Recode))+ geom_bar(fill='black',stat='count') + theme_bw_me + xlab("Facility") + ylab ("No. specimens") + theme(axis.ticks = element_line(color = "black"), axis.text = element_text(color = "black", size = 12), axis.title = element_text(size = 15)) +geom_text(stat='count', aes(label=..count..), vjust=-1, size = 4.5) + ylim(NA,max(max(table(df$LTACH_Recode)))+2)
# Number specimens per patients
patient_summaries <- df %>% group_by(Patient_ID) %>% summarise(n=n()) 
C <- ggplot(data=patient_summaries,aes(x=n)) + geom_bar(fill = "black", width = 0.7, stat = "count") + theme_bw_me + xlab("No. specimens") + ylab ("No. patients") + scale_y_continuous(limits = c(0, 300)) + theme(axis.ticks = element_line(color = "black"), axis.text = element_text(color = "black", size = 12), axis.title = element_text(size = 15)) +geom_text(stat='count', aes(label=..count..), vjust=-1, size = 4.5)

# Resistance proportion  
resistance_metl <- reshape2::melt(df %>% select(isolate_no,phenos),'isolate_no')
antibiotic_lookup <- c(
  TMP_SMX_dich = "TMP-SMX",
  gentamicin_dich = "Gentamicin",
  AMK_dich = "Amikacin",
  CST_dich = "Colistin",
  blbli_dich = "BL/BLI"
)

resistance_metl <- resistance_metl %>% mutate(variable = recode(as.character(variable), !!!antibiotic_lookup)) #rename var to antibiotic names
resistance_metl$value <- recode(resistance_metl$value, "Non-Susceptible" = "Resistant", "Susceptible" = "Susceptible") #rename val to resistance vs susceptible

res_order <- resistance_metl %>% group_by(variable) %>% summarise(prop_resistant = mean(value == "Resistant")) %>% arrange(desc(prop_resistant))

resistance_metl <- resistance_metl %>% mutate(variable = factor(variable, levels = res_order$variable))

D <- ggplot(data=resistance_metl,aes(x=variable,fill=value)) + geom_bar(width = 0.7, stat = "count") + scale_fill_manual(values = c("Resistant" = "black", "Susceptible" = "darkgray"), name = "Resistance Profile") + theme_bw_me + xlab("") + ylab ("No. specimens") + theme(
  legend.title = element_text(size = 13),
  legend.text = element_text(size = 12),
  legend.key.size = unit(0.3, "cm"),
  legend.spacing.x = unit(0.05, "cm"),
  axis.title.x = element_text(margin = margin(t = 2))) +
  theme(axis.ticks = element_line(color = "black"), axis.text = element_text(color = "black", size = 12), axis.title = element_text(size = 15))
```

```{r,fig.width=14,fig.height=9}
cowplot::plot_grid(A,B,C,D + theme(legend.position = "none"),ncol=2,labels = 'AUTO', label_size = 16, scale = c(0.95, 0.95, 0.95, 0.95)) -> fig1_wo_legend

cowplot::plot_grid(NULL, get_legend(D), ncol = 2) -> cowplot_legend 

cowplot::plot_grid(fig1_wo_legend, cowplot_legend + theme(plot.margin = unit(c(-1,0,0.2,0), "cm")), ncol = 1, rel_heights = c(1,0.025)) -> fig1

fig1

ggsave("./figures/figure1.png",fig1,dpi=600,width=14,height=9,bg='white')
```
