---
title: 'Supplemental Figure 2: Minimum-inhibitory concentration histograms'
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/')
```
 
# Environment
```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse","devtools","kableExtra","cowplot","gridExtra")   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

#Themes
source("./lib/consistent_themes.R")

# Scripts
source("./lib/common_functions.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data
```{r}
df <- readRDS("./data/dataset/df.RDS") 
```

# Function to create MIC histogram
```{r}
create_MIC_histogram <- function(phenotype_cont,phenotype_cat = NULL,phenotype_name){ 
    data <- bind_cols(phenotype_cont,phenotype_cat,quiet = TRUE)
    colnames(data) <- c("phenotype_cont","phenotype_cat")
    histogram <-  ggplot(data) +geom_bar(aes(x=phenotype_cont,fill=phenotype_cat)) + ylab("Number of isolates") + labs(fill="Resistance profile") +xlab(paste0(phenotype_name," (µg/mL)"))  + theme_bw_me 
  return(histogram)
} 
```

# MIC histograms
```{r,message=F,error=F,warning=F,fig.width=14,fig.height=7}
# Figure
sfig2a <- create_MIC_histogram(df$bactrim_mic,df$bactrim_cat,"TMP-SMX")  + ylim(NA,225) + sfigure_2_theme + resistance_cat_scale
  
sfig2b <-  create_MIC_histogram(df$gentamicin_mic,df$gentamicin_cat,"Gentamicin") + ylim(NA,225)+ sfigure_2_theme + resistance_cat_scale

sfig2c <-  create_MIC_histogram(df$AMK,df$AMK_cat,"Amikacin") + ylim(NA,225) + sfigure_2_theme + resistance_cat_scale

sfig2d <-  create_MIC_histogram(df$CST,df$CST_cat,"Colistin") + ylim(NA,225)+ sfigure_2_theme + resistance_cat_scale

sfig2e <- create_MIC_histogram(df$MVB_log_2,df$MVB_cat,"Meropenem-vaborbactam") + scale_x_continuous(breaks=c(-2,-1,0,1,2,3,4,5),
        labels=c("≤0.25","0.5", "1","2","4","8","16","≥32"))  + ylim(NA,225) + sfigure_2_theme + resistance_cat_scale
  
sfig2f <-  create_MIC_histogram(df$IR_log_2,df$IR_cat,"Imipenem-relebactam")+ scale_x_continuous(breaks=c(-2,-1,0,1,2,3,4,5),
        labels=c("≤0.25","0.5","1","2","4","8","16","≥32"))   + ylim(NA,225)+ sfigure_2_theme + resistance_cat_scale
# Legend
MIC_legend <- cowplot::get_plot_component(sfig2b,"guide-box",return_all=T) %>% .[[3]]
sfig2_legend_plot <- plot_grid(MIC_legend) + theme(plot.margin = unit(c(t=0, 0, 0, b=0), "cm"))

# Create cowplot Figure
sfig2_wo_legend <- plot_grid(sfig2a + theme(legend.position = "none"), sfig2b + theme(legend.position = "none"),
                            sfig2c + theme(legend.position = "none"), sfig2d + theme(legend.position = "none"),
                            sfig2e + theme(legend.position = "none"), sfig2f + theme(legend.position = "none"),ncol=3,labels = "AUTO",label_size = 18)

sfigure2 <- plot_grid(sfig2_wo_legend,sfig2_legend_plot, ncol=1,rel_heights = c(1,.1))
sfigure2
```

## Save file
```{r}
ggsave(filename = "~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/figures/sfigure2.png",plot=sfigure2,width = 14,height=7,dpi = 900,units = 'in',bg="white")
```
