---
title: "Supplemental Figure 5: Ancestral state reconstruction and evolutionary history inferences on the phylogenetic tree"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/')
```

# Environment
```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse","phyloAMR","ggtree","cowplot","gridExtra","hues")   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

#Themes
source("./lib/consistent_themes.R")

# Scripts
source("./lib/common_functions.R")

# Print environment
Sys.info()
sessionInfo()
```
 
# Load data
```{r}
# Patient Metadata & Phylogeny
df <- readRDS("./data/dataset/df.RDS")
tr <- read.tree("./data/tree/tree.treefile")   
df<- df %>% .[match(tr$tip.label,.$isolate_no),] 

# ASR models
pheno <- c("TMP_SMX","gentamicin","AMK","CST","blbli")
for(i in pheno){
  assign(paste0(i,"_asr"),readRDS(paste0("./data/asr_clustering/",i,"_asr.RDS")))
}

# ASR clustering
pheno <- c("TMP_SMX","gentamicin","AMK","CST","blbli")
for(i in pheno){
  assign(paste0(i,"_asr_clustering"),readRDS(paste0("./data/asr_clustering/",i,"_asr_clustering.RDS")))
}
```

# Paint trees
```{r,fig.width=10,fig.height=8.5} 
# Clustering scales
## Updated painted tree scale to ensure order
edge_color_updated <- scale_color_manual(breaks = c(1,0), values = c("red","black"), 
        labels = c("Present","Absent"), name = 'Trait',guide = guide_legend(ncol=1, order=1,title.position = "top", label.position = "right"))
  
state_parent_childs <- c()
for(i in pheno){
  state_parent_childs[[i]] <- get(paste0(i,"_asr")) %>% .$parent_child_df 
}
 
painted_trees <- lapply(state_parent_childs,FUN=function(x){
  paint_tree_with_states(parent_child_df = x,tr=tr) + edge_color_updated
  }) %>% `names<-`(pheno)

simple_consistent_theme <- theme(legend.position = 'right',legend.direction="vertical", legend.justification = "center",legend.box.spacing = unit(.001, "cm"),legend.key.size = unit(.75, "cm"),legend.key.width = unit(.75, "cm"),legend.spacing.x=unit(.75, "cm"))

painted_trees_w_cluster_calls <- lapply(pheno,FUN=function(x){
  p_obj <- painted_trees[[x]]
  asr_clustering_df <- get(paste0(x,"_asr_clustering")) %>% select(child_value,asr_cluster_renamed_resistant) %>% `colnames<-`(c("Resistance","Clustering")) %>% mutate_all(as.factor) 
  p1 <- gheatmap(p_obj,data=asr_clustering_df  %>% select(Resistance),width = 0.1,colnames_position = 'top',colnames_angle=90, colnames_offset_y = 0.5, hjust = 0, color = NA) + resistance_scale  + simple_consistent_theme
  p1.1 <- p1 + ggnewscale::new_scale_fill()
  p2 <- gheatmap(p1.1,data=asr_clustering_df  %>% select(Clustering),width = 0.1,colnames_position = 'top',colnames_angle=90, colnames_offset_y = 0.5, hjust = 0, color = NA,offset=0.000025)  + cluster_scale_3_col + ylim(NA,465)  + simple_consistent_theme
  p2
})

painted_trees_w_cluster_calls_wo_legends <- lapply(painted_trees_w_cluster_calls,FUN=function(x){x + theme(legend.position='none')
})
 
legend_fig <- cowplot::get_legend(painted_trees_w_cluster_calls[[3]])
 
names <- c("TMP-SMX","Gentamicin","Amikacin","Colistin","BL/BLI","")
max_value <- max(sapply(names,nchar))
consistent_names <- str_pad(string = names,width = max_value,side = 'right')


sfigure5 <- cowplot::plot_grid(painted_trees_w_cluster_calls_wo_legends[[1]],painted_trees_w_cluster_calls_wo_legends[[2]],painted_trees_w_cluster_calls_wo_legends[[3]],painted_trees_w_cluster_calls_wo_legends[[4]],painted_trees_w_cluster_calls_wo_legends[[5]],legend_fig,ncol=3,labels= consistent_names,label_x = 0,label_size = 14)

sfigure5
```

## Save file
```{r}
ggsave(filename = "~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/figures/sfigure5.png",plot=sfigure5,width = 10,height=8.5,dpi = 900,units = 'in',bg="white")
```
