---
title: "sfigure_3_paint_trees"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/')
```

# Environment
```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse","phyloAMR","ggtree","cowplot","gridExtra")   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

#Themes
source("./lib/consistent_themes.R")

# Scripts
source("./lib/common_functions.R")

# Print environment
Sys.info()
sessionInfo()
```
 
# Load data
```{r}
# Patient Metadata & Phylogeny
df <- readRDS("./data/dataset/df.RDS")
tr <- read.tree("./data/tree/tree.treefile")   
df<- df %>% .[match(tr$tip.label,.$isolate_no),] 

# ASR models
pheno <- c("TMP_SMX","gentamicin","AMK","CST","blbli")
for(i in pheno){
  assign(paste0(i,"_asr"),readRDS(paste0("./data/asr_clustering/",i,"_asr.RDS")))
}

# ASR clustering
pheno <- c("TMP_SMX","gentamicin","AMK","CST","blbli")
for(i in pheno){
  assign(paste0(i,"_asr_clustering"),readRDS(paste0("./data/asr_clustering/",i,"_asr_clustering.RDS")))
}
```

# Paint trees
```{r,fig.width=10,fig.height=8.5}
clustering_df <- readRDS("./data/asr_clustering/asr_clustering_df.RDS")
phenotypes <- c("TMP_SMX","gentamicin","AMK","CST","blbli") %>% paste0(.,"_asr_cluster")
sizes <- c()
for(i in phenotypes){
  sizes[i] <- table(clustering_df[,i])  %>% subset(names(.) != "singleton" & grepl("cluster_",names(.))) %>% as.numeric %>%length
}

ncluster <- max(sizes)
color_palette <- grDevices::colors() %>% subset(grepl("red",.)==F)
clusters_col <- hues::iwanthue(ncluster,hmin=25,hmax=360,lmin = 20,lmax = 95,cmin=5,cmax=90,random = F,plot = T)

clusters_name <- paste0("Resistant Cluster ",1:ncluster)
names(clusters_col) <- clusters_name

# Clustering scales
## Non-susceptible 
Non_sus_scale <- scale_fill_manual(breaks = c(0,1),values=c("white","black"),labels = c("Susceptible","Resistant"),name="Tip State",guide = guide_legend(title.position = "top", label.position = "right",nrow=2,order=2),drop = FALSE )

## cluster_scale
cluster_scale <- scale_fill_manual(breaks =c("Susceptible","Resistant Singleton",names(clusters_col)),values=c("Susceptible" = "white","Resistant Singleton" = "red",clusters_col),labels=c("Susceptible","R Singleton",gsub("Resistant","R",clusters_name)),name="Phylogenetics of Resistance", guide = guide_legend(ncol=3, order=3,title.position = "top", label.position = "right"))

state_parent_childs <- c()
for(i in pheno){
  state_parent_childs[[i]] <- get(paste0(i,"_asr")) %>% .$parent_child_df 
}
 
painted_trees <- lapply(state_parent_childs,paint_tree_with_states,tr)  %>% `names<-`(pheno)

painted_trees_w_cluster_calls <- lapply(pheno,FUN=function(x){
  p_obj <- painted_trees[[x]]
  asr_clustering_df <- get(paste0(x,"_asr_clustering")) %>% select(child_val,asr_cluster_renamed_resistant) %>% `colnames<-`(c("Feature","Clustering")) %>% mutate_all(as.factor) 
  p1 <- gheatmap(p_obj,data=asr_clustering_df  %>% select(Feature),width = 0.1,colnames_position = 'top',colnames_angle=90, colnames_offset_y = 0.25, hjust = 0, color = NA) + Non_sus_scale
  p1.1 <- p1 + ggnewscale::new_scale_fill()
  p2 <- gheatmap(p1.1,data=asr_clustering_df  %>% select(Clustering),width = 0.1,colnames_position = 'top',colnames_angle=90, colnames_offset_y = 0.25, hjust = 0, color = NA,offset=0.000025)  + cluster_scale + ylim(NA,450)
  p2
})

painted_trees_w_cluster_calls_wo_legends <- lapply(painted_trees_w_cluster_calls,FUN=function(x){x + theme(legend.position='none')
})
 
legend_fig <- cowplot::get_legend(painted_trees_w_cluster_calls[[3]])
 
sfigure2 <- cowplot::plot_grid(painted_trees_w_cluster_calls_wo_legends[[1]],painted_trees_w_cluster_calls_wo_legends[[2]],painted_trees_w_cluster_calls_wo_legends[[3]],painted_trees_w_cluster_calls_wo_legends[[4]],painted_trees_w_cluster_calls_wo_legends[[5]],legend_fig,ncol=3,labels =c("A TMP-SMX","B Gentamicin","C Amikacin","D Colistin","E BL/BLI",""),label_x = 0,label_size = 12)

sfigure2
```

## Save file
```{r}
ggsave(filename = "~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/figures/sfigure2.png",plot=sfigure2,width = 10,height=8.5,dpi = 600,units = 'in',bg="white")
```
