---
title: 'Supplemental Figure 1: MIC Histogram'
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/')
```
 
# Environment
```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse","devtools","kableExtra","cowplot","gridExtra")   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

#Themes
source("./lib/consistent_themes.R")

# Scripts
source("./lib/common_functions.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data
```{r}
df <- readRDS("./data/dataset/df.RDS") 
```

# Function to create MIC histogram
```{r}
create_MIC_histogram <- function(phenotype_cont,phenotype_cat = NULL,phenotype_name,title){ 
    data <- bind_cols(phenotype_cont,phenotype_cat,quiet = TRUE)
    colnames(data) <- c("phenotype_cont","phenotype_cat")
    histogram <-  ggplot(data) +geom_bar(aes(x=phenotype_cont,fill=phenotype_cat)) + ylab("Number of Isolates") + labs(fill="Resistance Profile") +ylab("Number of Isolates") +xlab(paste0(phenotype_name," MIC (µg/mL)"))  +  ggtitle(paste0(title))  +theme_bw_me 
  return(histogram)
} 
```

# MIC histograms
```{r,message=F,error=F,warning=F,fig.width=19,fig.height=9.5}
# Figure
sfig1a <- create_MIC_histogram(df$bactrim_mic,df$bactrim_cat,"TMP-SMX","A.")  + ylim(NA,225) + format + resistance_cat_scale
  
sfig1b <-  create_MIC_histogram(df$gentamicin_mic,df$gentamicin_cat,"Gentamicin","B.") + ylim(NA,225)+ format + resistance_cat_scale

sfig1c <-  create_MIC_histogram(df$AMK,df$AMK_cat,"Amikacin","C.") + ylim(NA,225) + format + resistance_cat_scale

sfig1d <-  create_MIC_histogram(df$CST,df$CST_cat,"Colistin","D.") + ylim(NA,225)+ format + resistance_cat_scale

sfig1e <- create_MIC_histogram(df$MVB_log_2,df$MVB_cat,"Meropenem-Vaborbactam","E.") + scale_x_continuous(breaks=c(-2,-1,0,1,2,3,4,5),
        labels=c("≤0.25","0.5", "1","2","4","8","16","≥32"))  + ylim(NA,225) + format + resistance_cat_scale
  
sfig1f <-  create_MIC_histogram(df$IR_log_2,df$IR_cat,"Imipenem-Relebactam","F.")+ scale_x_continuous(breaks=c(-2,-1,0,1,2,3,4,5),
        labels=c("≤0.25","0.5","1","2","4","8","16","≥32"))   + ylim(NA,225)+ format + resistance_cat_scale
# Legend
MIC_legend <- cowplot::get_plot_component(sfig1b,"guide-box",return_all=T) %>% .[[3]]
sfig1_legend_plot <- plot_grid(MIC_legend) + theme(plot.margin = unit(c(t=-1, 0, 0, b=0), "cm"))

# Create cowplot Figure
sfig1_wo_legend <- plot_grid(sfig1a + theme(legend.position = "none"),sfig1b + theme(legend.position = "none"),
                            sfig1c + theme(legend.position = "none"),sfig1d + theme(legend.position = "none"),
                            sfig1e + theme(legend.position = "none"),sfig1f + theme(legend.position = "none"),ncol=3)
sfig1 <- plot_grid(sfig1_wo_legend,sfig1_legend_plot, ncol=1,rel_heights = c(1,.2))
sfig1
```

## Save file
```{r}
ggsave(filename = "~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/figures/sfigure1.png",plot=sfig1,width = 19,height=9.5,dpi = 600,units = 'in',bg="white") 
```
