---
title: "Generate phylogenetic clustering data frame for downstream analyses"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/')
```

# Environment
```{r environment, echo=T, message=T, include=T, results=T}
#Packages
packages <- c("tidyverse")   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T)) 
# Load function
source('./lib/consistent_themes.R')
# Print
Sys.info()
sessionInfo() 
``` 

# Load data
```{r load data,include=T,echo=T,results=F,message=F} 
# Patient Metadata
df <- readRDS("./data/dataset/df.RDS")
# Best model call
pheno <- c("TMP_SMX","gentamicin","AMK","CST","blbli")
for(i in pheno){
  assign(x = paste0(i,"_asr_clustering"),readRDS(file = paste0("./data/asr_clustering/",i,"_asr_clustering.RDS")))
} 
```

# Extract asr clustering dataframe and merge together
```{r}
extract_dataset <- function(pheno){
  obj <- get(paste0(pheno,"_asr_clustering") )
  final_df <- obj %>% select("child_name","asr_cluster","asr_cluster_renamed","asr_cluster_renamed_resistant","asr_cluster_collapsed") %>% `colnames<-`(c("isolate_no",paste0(pheno,"_",colnames(.[,2:5])))) %>% as.data.frame
  return(final_df)
}

pclustering_df <- lapply(pheno,extract_dataset)  %>% Reduce(function(df1,df2) left_join(df1,df2),.) 
```

# Preview figure
```{r}
head(pclustering_df) %>% favorite_kable()
```

# Save dataset
```{r}
saveRDS(pclustering_df,"./data/asr_clustering/asr_clustering_df.RDS")
```
