---
title: "generate_asr_transition_stats"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/')
```

# Environment
```{r environment, echo=T, message=T, include=T, results=T}
#Packages
packages <- c("tidyverse",'phyloAMR')   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T)) 
# Load function
source('./lib/consistent_themes.R')
# Print
Sys.info()
sessionInfo() 
``` 

# Load datasets
```{r load data,include=T,echo=T,results=F,message=F} 
# Patient Metadata
df <- readRDS("./data/dataset/df.RDS")
# Best model call
pheno <- c("TMP_SMX","gentamicin","AMK","CST","blbli")
for(i in pheno){
  assign(x = paste0(i,"_asr"),readRDS(file = paste0("./data/asr_clustering/",i,"_asr.RDS")))
} 
```

# Get parent child dataframes
```{r}
parent_dfs <- lapply(paste0(pheno,"_asr"),get) %>% lapply(.,FUN=function(x){x[["parent_child_df"]]}) %>% `names<-`(pheno)
```

# Transition Analysis 
```{r}
transition_stats <- lapply(parent_dfs, asr_transition_analysis, node_states="joint") %>% do.call(rbind,.) %>% mutate(pheno = pheno)  %>% `rownames<-`(NULL)

favorite_kable(transition_stats)

# Save
saveRDS(transition_stats,"./data/asr_clustering/transition_stats.RDS")
```
