---
title: "Supplemental Table 4: Comparison of ancestral state reconstruction models using Akaike information criteria"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Phyloaware/phylogenetic-resistance-ms/')
```

# Environment
```{r environment, echo=T, message=T, include=T, results=T}
#Packages
packages <- c("tidyverse")   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T)) 

# Load function
source('./lib/consistent_themes.R')

# Print
Sys.info()
sessionInfo() 
``` 

# Load data
```{r load data}
# ASR models
pheno <- c("TMP_SMX","gentamicin","AMK","CST","blbli")

asr_model_characteristics <- lapply(pheno,FUN=function(i){
  obj <- readRDS(paste0("./data/asr_clustering/",i,"_asr.RDS"))
  obj[["corHMM_model_statistics"]][["pheno"]] <-  i
  obj[["corHMM_model_statistics"]]
}) %>% do.call(rbind,.)
```

# Create table 

## Format
```{r} 
stable4 <- asr_model_characteristics %>%  select(pheno,model,number_parameters,rate1,rate2,loglik,AICc,best_model) %>% `colnames<-`(c("Phenotype","Model","No. Parameters","Rate 1","Rate 2","Log Likelihood","Corrected AIC","Best model")) %>% `rownames<-`(NULL) 

stable4$`Log Likelihood` <- formatC(stable4$`Log Likelihood`,format = "f",digits =2)
stable4$`Corrected AIC` <-  formatC(stable4$`Log Likelihood`,format = "f",digits =2)

stable4$Phenotype <- recode(stable4$Phenotype,'TMP_SMX'='TMP-SMX',
                             "gentamicin"="Gentamicin",
                             'AMK_dich'='Amikacin',
                             'CST'='Colistin',
                             'blbli'="BL/BLI")    

stable4 %>% favorite_kable 
```

# Save table
```{r}
saveRDS(stable4,"./tables/stable4.RDS")
write_csv(stable4,"./tables/stable4.csv")
``` 
